# This is a basic workflow to help you get started with Actions

name: Azure Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout' 
        uses: actions/checkout@master
      - name: 'Deploy to Azure'
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: homelifecompanion
          publish-profile: ${{ secrets.azurePublishProfile }}
